# Generated by Django 3.2.2 on 2022-04-30 18:36

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('vote_average', models.FloatField()),
                ('local_rating', models.FloatField(null=True)),
            ],
        ),
    ]
